# This file defines LLSM's default pipeline, which runs all steps in the
# azure-ci-job.yml template. The default pipeline runs on each push to master.

# Run this pipeline when we push to master. If the changes are only to non-code
# files, do not run this pipeline.
trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - .clang-format
      - .gitignore
      - AUTHORS
      - LICENSE
      - README.md

jobs:
    template: azure-ci-job.yml
    parameters:
      jobName: MasterPushCheck
      jobDisplayName: Build, Run Tests, Run Checks (All)
      buildType: Debug
      skipTests: false
      # Valgrind does not support some instructions that LLSM uses.
      skipValgrind: true
      memcheckTestFilter: '*'
