# This file defines LLSM's pull request pipeline, which runs all steps in the
# azure-ci-job.yml template but will only run Valgrind Memcheck on tests with
# names that match the 'DBTest.*' regex. This pipeline runs when a pull request
# is opened and should complete faster than the default pipeline.

# This pipeline is only triggered by pull requests (configured separately).
trigger: none

jobs:
  - template: azure-ci-job.yml
    parameters:
      jobName: PullRequestCheck
      jobDisplayName: Build, Run Tests, Run Checks (on DBTest Only)
      buildType: Debug
      skipTests: false
      # Valgrind does not support some instructions that LLSM uses.
      skipValgrind: true
      memcheckTestFilter: 'DBTest.*'
