name: Testing Suite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install TBB
      run: sudo apt-get install libtbb-dev
      
    - name: Configure Project using CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DLLSM_BUILD_TESTS=ON -DLLSM_BUILD_BENCHMARKS=OFF

    - name: Compile Project 
      working-directory: ${{github.workspace}}/build
      run: make -j
      timeout-minutes: 15
      
    - name: Run Tests using CTest
      working-directory: ${{github.workspace}}/build
      run: ctest -T Test
      timeout-minutes: 15




